baseURL = 'https://roneo.itcouldbewor.se/'
languageCode = 'en-us'
defaultContentLanguage = 'en'


[params]
  title = 'Evolution Engine - Understanding the world through the lens of evolution'
  metaDescription = "Evolution Engine is a project that aims to explain the world through the lens of evolution. It's a simulation of evolution that allows you to see how different factors affect the evolution of a population of creatures."


# Languages
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
mark = "EN"


[taxonomies]
  category= "theme"
  scene = "scenes"
